// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW2598DUgj1Jotar5PqkxlFbEPL2NYvyA',
    appId: '1:677297770562:web:c9ccb0836367d94db95ddb',
    messagingSenderId: '677297770562',
    projectId: 'video-chat-68cdb',
    authDomain: 'video-chat-68cdb.firebaseapp.com',
    storageBucket: 'video-chat-68cdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeRrjwjO02QowrLEjdEK3wnV0rxLpj50Y',
    appId: '1:677297770562:android:37aa9fd2a9b9adf9b95ddb',
    messagingSenderId: '677297770562',
    projectId: 'video-chat-68cdb',
    storageBucket: 'video-chat-68cdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6e4wWksirfLDQUz2joOCdSeyJqCIctls',
    appId: '1:677297770562:ios:2984078b3103c04db95ddb',
    messagingSenderId: '677297770562',
    projectId: 'video-chat-68cdb',
    storageBucket: 'video-chat-68cdb.appspot.com',
    iosBundleId: 'com.example.videoChat',
  );
}
